---
name: ci

on:
  push:
    branches:
      - feature/*
      - fix/*
      - refactor/*
  pull_request:
    branches:
      - main
      - feature/*
      - fix/*
      - refactor/*
  workflow_dispatch: # 手動トリガー用

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  njsscan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
        with:
          args: '. --sarif --output results.sarif || true'
      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4
      - name: GitHub CLIをインストール
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y
      - name: 既存のプルリクエストをチェック
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          gh pr list --head "${HEAD_REF}" --json number --jq .[0].number > pr_number.txt
          if [ -s pr_number.txt ]; then
            echo "PR_EXISTS=true" >> $GITHUB_ENV
            echo "pr_exists=true" >> $GITHUB_OUTPUT
          else
            echo "PR_EXISTS=false" >> $GITHUB_ENV
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          fi

  create-pull-request:
    needs: [njsscan, check_pr]
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4
      - name: プルリクエストを作成
        if: steps.check_pr.outputs.pr_exists == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated PR: Lint and NJSSCAN results"
          body: |
            This PR is automatically generated by the CI workflow.
            - Linting and NJSSCAN checks have passed.
          base: main
          branch: ${{ github.head_ref }}
